import React from 'react';
import { ArrowRight, CalendarClock, Check, Languages, MessageCircleMore, Mic2, Stethoscope, TestTube2, UsersRound } from 'lucide-react';

const programs = [
  { icon: TestTube2, title: 'IELTS Preparation', text: 'Academic and General Training pathways with mock tests, writing feedback, and speaking practice.', points: ['Diagnostic test', 'Band-focused plan', 'Full mock exams'] },
  { icon: Stethoscope, title: 'OET Training', text: 'Healthcare-focused English preparation with profession-specific writing and role-play practice.', points: ['Medical scenarios', 'Letter correction', 'Speaking role-play'] },
  { icon: Mic2, title: 'Spoken English', text: 'Build confidence for academic interviews, presentations, daily communication, and campus life.', points: ['Interactive sessions', 'Pronunciation support', 'Public speaking'] },
  { icon: Languages, title: 'German Language', text: 'Structured A1–B2 learning for study, work, integration, and university pathway preparation.', points: ['Level-based batches', 'Exam preparation', 'Cultural orientation'] },
];

export const LanguageAcademyView = ({ onNavigate }) => (
  <div className="bg-white text-slate-900">
    <section className="relative overflow-hidden bg-[#052b50] px-5 py-20 text-white sm:px-8 lg:px-12 lg:py-24"><div className="absolute -bottom-44 -right-36 h-[30rem] w-[30rem] rounded-full border-[76px] border-white/[0.04]" aria-hidden="true" /><div className="relative mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_0.7fr] lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-sky-300">Language Academy</p><h1 className="font-display mt-5 text-[clamp(3rem,6vw,5rem)] font-semibold leading-[1.02] tracking-[-0.05em]">Prepare your language. Expand your future.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-sky-100/70">Language preparation for university admissions, professional registration, interviews, and confident international study.</p><button type="button" onClick={() => onNavigate('contact')} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-4 text-sm font-extrabold text-[#075ec5]">Ask about the next batch <ArrowRight className="h-4 w-4" /></button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{[[UsersRound, 'Small-group and one-to-one options'], [CalendarClock, 'Weekday, evening, and weekend preferences'], [MessageCircleMore, 'Regular feedback and progress reviews']].map(([Icon, label]) => <div key={label} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.06] p-4"><Icon className="h-5 w-5 text-sky-300" /><span className="text-xs font-bold text-sky-50/85">{label}</span></div>)}</div></div></section>
    <section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><div className="max-w-3xl"><p className="eyebrow">Choose your pathway</p><h2 className="font-display mt-4 text-4xl font-semibold tracking-[-0.04em] text-[#062d55]">Practical preparation for real goals.</h2><p className="mt-4 text-sm leading-7 text-slate-600">Batch availability and course schedules are confirmed after an initial level and goal discussion.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{programs.map(({ icon: Icon, title, text, points }) => <article key={title} className="rounded-[1.75rem] border border-slate-200 bg-[#fbfdff] p-6 transition hover:-translate-y-1 hover:shadow-[0_20px_50px_rgba(6,45,85,0.1)] sm:p-8"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-[#075ec5]"><Icon className="h-7 w-7" /></span><h3 className="font-display mt-6 text-2xl font-semibold text-[#062d55]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p><div className="mt-5 flex flex-wrap gap-2">{points.map((point) => <span key={point} className="inline-flex items-center gap-1.5 rounded-full bg-white px-3 py-2 text-[10px] font-bold text-slate-600 ring-1 ring-slate-200"><Check className="h-3 w-3 text-emerald-500" /> {point}</span>)}</div><button type="button" onClick={() => onNavigate('contact')} className="mt-6 inline-flex items-center gap-2 text-xs font-extrabold text-[#075ec5]">Enquire about {title} <ArrowRight className="h-4 w-4" /></button></article>)}</div></div></section>
    <section className="bg-[#f4f9fc] px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-[1280px] gap-8 rounded-[2rem] bg-gradient-to-r from-[#063d78] to-[#075ec5] p-8 text-white sm:p-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><h2 className="font-display text-3xl font-semibold">Need IELTS, OET, spoken English, or German guidance?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-blue-50/75">Send your current level, target score, deadline, and preferred schedule. A counselor will recommend the right preparation route.</p></div><button type="button" onClick={() => onNavigate('contact')} className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-[#075ec5]">Book a language consultation <ArrowRight className="h-4 w-4" /></button></div></section>
  </div>
);
